// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.3.0
// source: repository_integrator.proto

package repository_integrator

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntegrationType int32

const (
	IntegrationType_GITHUB_OAUTH_TOKEN IntegrationType = 0
	IntegrationType_GITHUB_APP         IntegrationType = 1
	IntegrationType_BITBUCKET          IntegrationType = 2
	IntegrationType_GITLAB             IntegrationType = 3
	IntegrationType_GIT                IntegrationType = 4
)

// Enum value maps for IntegrationType.
var (
	IntegrationType_name = map[int32]string{
		0: "GITHUB_OAUTH_TOKEN",
		1: "GITHUB_APP",
		2: "BITBUCKET",
		3: "GITLAB",
		4: "GIT",
	}
	IntegrationType_value = map[string]int32{
		"GITHUB_OAUTH_TOKEN": 0,
		"GITHUB_APP":         1,
		"BITBUCKET":          2,
		"GITLAB":             3,
		"GIT":                4,
	}
)

func (x IntegrationType) Enum() *IntegrationType {
	p := new(IntegrationType)
	*p = x
	return p
}

func (x IntegrationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntegrationType) Descriptor() protoreflect.EnumDescriptor {
	return file_repository_integrator_proto_enumTypes[0].Descriptor()
}

func (IntegrationType) Type() protoreflect.EnumType {
	return &file_repository_integrator_proto_enumTypes[0]
}

func (x IntegrationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntegrationType.Descriptor instead.
func (IntegrationType) EnumDescriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{0}
}

type IntegrationScope int32

const (
	IntegrationScope_FULL_CONNECTION IntegrationScope = 0
	IntegrationScope_ONLY_PUBLIC     IntegrationScope = 1
	IntegrationScope_NO_CONNECTION   IntegrationScope = 2
)

// Enum value maps for IntegrationScope.
var (
	IntegrationScope_name = map[int32]string{
		0: "FULL_CONNECTION",
		1: "ONLY_PUBLIC",
		2: "NO_CONNECTION",
	}
	IntegrationScope_value = map[string]int32{
		"FULL_CONNECTION": 0,
		"ONLY_PUBLIC":     1,
		"NO_CONNECTION":   2,
	}
)

func (x IntegrationScope) Enum() *IntegrationScope {
	p := new(IntegrationScope)
	*p = x
	return p
}

func (x IntegrationScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntegrationScope) Descriptor() protoreflect.EnumDescriptor {
	return file_repository_integrator_proto_enumTypes[1].Descriptor()
}

func (IntegrationScope) Type() protoreflect.EnumType {
	return &file_repository_integrator_proto_enumTypes[1]
}

func (x IntegrationScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntegrationScope.Descriptor instead.
func (IntegrationScope) EnumDescriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{1}
}

// Get Token call request
//
// - user_id          = [required if integration_type == GIT_HUB_OAUTH_TOKEN] UUID of the user.
// - repository_slug  = [required if integration_type == GIT_HUB_APP] name of an repository.
// - integration_type = [required if project_id is nil] type of an integration.
// - project_id       = [required if integration_type is nil]
type GetTokenRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RepositorySlug  string                 `protobuf:"bytes,2,opt,name=repository_slug,json=repositorySlug,proto3" json:"repository_slug,omitempty"`
	IntegrationType IntegrationType        `protobuf:"varint,3,opt,name=integration_type,json=integrationType,proto3,enum=InternalApi.RepositoryIntegrator.IntegrationType" json:"integration_type,omitempty"`
	ProjectId       string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_repository_integrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{0}
}

func (x *GetTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTokenRequest) GetRepositorySlug() string {
	if x != nil {
		return x.RepositorySlug
	}
	return ""
}

func (x *GetTokenRequest) GetIntegrationType() IntegrationType {
	if x != nil {
		return x.IntegrationType
	}
	return IntegrationType_GITHUB_OAUTH_TOKEN
}

func (x *GetTokenRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// Get Token call response
//
// - token      = [required] token for integration.
// - expired_at = [optional] exporation date of a token.
type GetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_repository_integrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{1}
}

func (x *GetTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetTokenResponse) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Check Token call request
//
// - project_id       = [required] UUID of the project
type CheckTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenRequest) Reset() {
	*x = CheckTokenRequest{}
	mi := &file_repository_integrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenRequest) ProtoMessage() {}

func (x *CheckTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenRequest.ProtoReflect.Descriptor instead.
func (*CheckTokenRequest) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{2}
}

func (x *CheckTokenRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// Check Token call response
//
// - valid             = [required] state of a token.
// - integration_scope = [required] scope of a connection
type CheckTokenResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Valid            bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	IntegrationScope IntegrationScope       `protobuf:"varint,2,opt,name=integration_scope,json=integrationScope,proto3,enum=InternalApi.RepositoryIntegrator.IntegrationScope" json:"integration_scope,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckTokenResponse) Reset() {
	*x = CheckTokenResponse{}
	mi := &file_repository_integrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenResponse) ProtoMessage() {}

func (x *CheckTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenResponse.ProtoReflect.Descriptor instead.
func (*CheckTokenResponse) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{3}
}

func (x *CheckTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *CheckTokenResponse) GetIntegrationScope() IntegrationScope {
	if x != nil {
		return x.IntegrationScope
	}
	return IntegrationScope_FULL_CONNECTION
}

// PreheatFileCache call request
//
//   - project_id = [required] UUID of the project
//   - path       = [required] Path of a file in a repo
//   - ref        = [optional] The name of the commit/branch/tag.
//     Default: the repository’s default branch.
type PreheatFileCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreheatFileCacheRequest) Reset() {
	*x = PreheatFileCacheRequest{}
	mi := &file_repository_integrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreheatFileCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreheatFileCacheRequest) ProtoMessage() {}

func (x *PreheatFileCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreheatFileCacheRequest.ProtoReflect.Descriptor instead.
func (*PreheatFileCacheRequest) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{4}
}

func (x *PreheatFileCacheRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PreheatFileCacheRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PreheatFileCacheRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

// Get File call request
//
//   - project_id = [required] UUID of the project
//   - path       = [required] Path of a file in a repo
//   - ref        = [optional] The name of the commit/branch/tag.
//     Default: the repository’s default branch.
type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_repository_integrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetFileRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

// Get File call response
//
// - content = [required] base64 encoded content of a file.
type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_repository_integrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// GithubInstallationInfo call request
//
// - project_id       = [required] UUID of the project
type GithubInstallationInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubInstallationInfoRequest) Reset() {
	*x = GithubInstallationInfoRequest{}
	mi := &file_repository_integrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubInstallationInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubInstallationInfoRequest) ProtoMessage() {}

func (x *GithubInstallationInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubInstallationInfoRequest.ProtoReflect.Descriptor instead.
func (*GithubInstallationInfoRequest) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{7}
}

func (x *GithubInstallationInfoRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// GithubInstallationInfo call response
//
// - installation_id  = [optional] id of an github app installation, if present
// - application_url  = [required] URL to github app
// - installation_url = [optional] URL to github app installation, if present
type GithubInstallationInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstallationId  int64                  `protobuf:"varint,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	ApplicationUrl  string                 `protobuf:"bytes,2,opt,name=application_url,json=applicationUrl,proto3" json:"application_url,omitempty"`
	InstallationUrl string                 `protobuf:"bytes,3,opt,name=installation_url,json=installationUrl,proto3" json:"installation_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GithubInstallationInfoResponse) Reset() {
	*x = GithubInstallationInfoResponse{}
	mi := &file_repository_integrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubInstallationInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubInstallationInfoResponse) ProtoMessage() {}

func (x *GithubInstallationInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubInstallationInfoResponse.ProtoReflect.Descriptor instead.
func (*GithubInstallationInfoResponse) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{8}
}

func (x *GithubInstallationInfoResponse) GetInstallationId() int64 {
	if x != nil {
		return x.InstallationId
	}
	return 0
}

func (x *GithubInstallationInfoResponse) GetApplicationUrl() string {
	if x != nil {
		return x.ApplicationUrl
	}
	return ""
}

func (x *GithubInstallationInfoResponse) GetInstallationUrl() string {
	if x != nil {
		return x.InstallationUrl
	}
	return ""
}

// InitGithubInstallation call request
// Used by bootstrapper to initialize github app installations
type InitGithubInstallationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitGithubInstallationRequest) Reset() {
	*x = InitGithubInstallationRequest{}
	mi := &file_repository_integrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitGithubInstallationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitGithubInstallationRequest) ProtoMessage() {}

func (x *InitGithubInstallationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitGithubInstallationRequest.ProtoReflect.Descriptor instead.
func (*InitGithubInstallationRequest) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{9}
}

type InitGithubInstallationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitGithubInstallationResponse) Reset() {
	*x = InitGithubInstallationResponse{}
	mi := &file_repository_integrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitGithubInstallationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitGithubInstallationResponse) ProtoMessage() {}

func (x *InitGithubInstallationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitGithubInstallationResponse.ProtoReflect.Descriptor instead.
func (*InitGithubInstallationResponse) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{10}
}

// Get Repositories call request
//
// - user_id          = [required] UUID of the user.
// - integration_type = [required] type of an integration.
type GetRepositoriesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IntegrationType IntegrationType        `protobuf:"varint,2,opt,name=integration_type,json=integrationType,proto3,enum=InternalApi.RepositoryIntegrator.IntegrationType" json:"integration_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRepositoriesRequest) Reset() {
	*x = GetRepositoriesRequest{}
	mi := &file_repository_integrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoriesRequest) ProtoMessage() {}

func (x *GetRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{11}
}

func (x *GetRepositoriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRepositoriesRequest) GetIntegrationType() IntegrationType {
	if x != nil {
		return x.IntegrationType
	}
	return IntegrationType_GITHUB_OAUTH_TOKEN
}

// Get Repositories call response
//
// - repositories = [required] List of repositories visable to user.
type GetRepositoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*Repository          `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoriesResponse) Reset() {
	*x = GetRepositoriesResponse{}
	mi := &file_repository_integrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoriesResponse) ProtoMessage() {}

func (x *GetRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{12}
}

func (x *GetRepositoriesResponse) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addable       bool                   `protobuf:"varint,1,opt,name=addable,proto3" json:"addable,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_repository_integrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_repository_integrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_repository_integrator_proto_rawDescGZIP(), []int{13}
}

func (x *Repository) GetAddable() bool {
	if x != nil {
		return x.Addable
	}
	return false
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Repository) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Repository) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_repository_integrator_proto protoreflect.FileDescriptor

const file_repository_integrator_proto_rawDesc = "" +
	"\n" +
	"\x1brepository_integrator.proto\x12 InternalApi.RepositoryIntegrator\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd0\x01\n" +
	"\x0fGetTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0frepository_slug\x18\x02 \x01(\tR\x0erepositorySlug\x12\\\n" +
	"\x10integration_type\x18\x03 \x01(\x0e21.InternalApi.RepositoryIntegrator.IntegrationTypeR\x0fintegrationType\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\"c\n" +
	"\x10GetTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"2\n" +
	"\x11CheckTokenRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\x8b\x01\n" +
	"\x12CheckTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12_\n" +
	"\x11integration_scope\x18\x02 \x01(\x0e22.InternalApi.RepositoryIntegrator.IntegrationScopeR\x10integrationScope\"^\n" +
	"\x17PreheatFileCacheRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\"U\n" +
	"\x0eGetFileRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\"+\n" +
	"\x0fGetFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\">\n" +
	"\x1dGithubInstallationInfoRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\x9d\x01\n" +
	"\x1eGithubInstallationInfoResponse\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\x03R\x0einstallationId\x12'\n" +
	"\x0fapplication_url\x18\x02 \x01(\tR\x0eapplicationUrl\x12)\n" +
	"\x10installation_url\x18\x03 \x01(\tR\x0finstallationUrl\"\x1f\n" +
	"\x1dInitGithubInstallationRequest\" \n" +
	"\x1eInitGithubInstallationResponse\"\x8f\x01\n" +
	"\x16GetRepositoriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\\\n" +
	"\x10integration_type\x18\x02 \x01(\x0e21.InternalApi.RepositoryIntegrator.IntegrationTypeR\x0fintegrationType\"k\n" +
	"\x17GetRepositoriesResponse\x12P\n" +
	"\frepositories\x18\x01 \x03(\v2,.InternalApi.RepositoryIntegrator.RepositoryR\frepositories\"\x8b\x01\n" +
	"\n" +
	"Repository\x12\x18\n" +
	"\aaddable\x18\x01 \x01(\bR\aaddable\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription*]\n" +
	"\x0fIntegrationType\x12\x16\n" +
	"\x12GITHUB_OAUTH_TOKEN\x10\x00\x12\x0e\n" +
	"\n" +
	"GITHUB_APP\x10\x01\x12\r\n" +
	"\tBITBUCKET\x10\x02\x12\n" +
	"\n" +
	"\x06GITLAB\x10\x03\x12\a\n" +
	"\x03GIT\x10\x04*K\n" +
	"\x10IntegrationScope\x12\x13\n" +
	"\x0fFULL_CONNECTION\x10\x00\x12\x0f\n" +
	"\vONLY_PUBLIC\x10\x01\x12\x11\n" +
	"\rNO_CONNECTION\x10\x022\xa5\a\n" +
	"\x1bRepositoryIntegratorService\x12q\n" +
	"\bGetToken\x121.InternalApi.RepositoryIntegrator.GetTokenRequest\x1a2.InternalApi.RepositoryIntegrator.GetTokenResponse\x12w\n" +
	"\n" +
	"CheckToken\x123.InternalApi.RepositoryIntegrator.CheckTokenRequest\x1a4.InternalApi.RepositoryIntegrator.CheckTokenResponse\x12e\n" +
	"\x10PreheatFileCache\x129.InternalApi.RepositoryIntegrator.PreheatFileCacheRequest\x1a\x16.google.protobuf.Empty\x12n\n" +
	"\aGetFile\x120.InternalApi.RepositoryIntegrator.GetFileRequest\x1a1.InternalApi.RepositoryIntegrator.GetFileResponse\x12\x9b\x01\n" +
	"\x16GithubInstallationInfo\x12?.InternalApi.RepositoryIntegrator.GithubInstallationInfoRequest\x1a@.InternalApi.RepositoryIntegrator.GithubInstallationInfoResponse\x12\x9b\x01\n" +
	"\x16InitGithubInstallation\x12?.InternalApi.RepositoryIntegrator.InitGithubInstallationRequest\x1a@.InternalApi.RepositoryIntegrator.InitGithubInstallationResponse\x12\x86\x01\n" +
	"\x0fGetRepositories\x128.InternalApi.RepositoryIntegrator.GetRepositoriesRequest\x1a9.InternalApi.RepositoryIntegrator.GetRepositoriesResponseBEZCgithub.com/superplanehq/superplane/pkg/protos/repository_integratorb\x06proto3"

var (
	file_repository_integrator_proto_rawDescOnce sync.Once
	file_repository_integrator_proto_rawDescData []byte
)

func file_repository_integrator_proto_rawDescGZIP() []byte {
	file_repository_integrator_proto_rawDescOnce.Do(func() {
		file_repository_integrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repository_integrator_proto_rawDesc), len(file_repository_integrator_proto_rawDesc)))
	})
	return file_repository_integrator_proto_rawDescData
}

var file_repository_integrator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_repository_integrator_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_repository_integrator_proto_goTypes = []any{
	(IntegrationType)(0),                   // 0: InternalApi.RepositoryIntegrator.IntegrationType
	(IntegrationScope)(0),                  // 1: InternalApi.RepositoryIntegrator.IntegrationScope
	(*GetTokenRequest)(nil),                // 2: InternalApi.RepositoryIntegrator.GetTokenRequest
	(*GetTokenResponse)(nil),               // 3: InternalApi.RepositoryIntegrator.GetTokenResponse
	(*CheckTokenRequest)(nil),              // 4: InternalApi.RepositoryIntegrator.CheckTokenRequest
	(*CheckTokenResponse)(nil),             // 5: InternalApi.RepositoryIntegrator.CheckTokenResponse
	(*PreheatFileCacheRequest)(nil),        // 6: InternalApi.RepositoryIntegrator.PreheatFileCacheRequest
	(*GetFileRequest)(nil),                 // 7: InternalApi.RepositoryIntegrator.GetFileRequest
	(*GetFileResponse)(nil),                // 8: InternalApi.RepositoryIntegrator.GetFileResponse
	(*GithubInstallationInfoRequest)(nil),  // 9: InternalApi.RepositoryIntegrator.GithubInstallationInfoRequest
	(*GithubInstallationInfoResponse)(nil), // 10: InternalApi.RepositoryIntegrator.GithubInstallationInfoResponse
	(*InitGithubInstallationRequest)(nil),  // 11: InternalApi.RepositoryIntegrator.InitGithubInstallationRequest
	(*InitGithubInstallationResponse)(nil), // 12: InternalApi.RepositoryIntegrator.InitGithubInstallationResponse
	(*GetRepositoriesRequest)(nil),         // 13: InternalApi.RepositoryIntegrator.GetRepositoriesRequest
	(*GetRepositoriesResponse)(nil),        // 14: InternalApi.RepositoryIntegrator.GetRepositoriesResponse
	(*Repository)(nil),                     // 15: InternalApi.RepositoryIntegrator.Repository
	(*timestamp.Timestamp)(nil),            // 16: google.protobuf.Timestamp
	(*empty.Empty)(nil),                    // 17: google.protobuf.Empty
}
var file_repository_integrator_proto_depIdxs = []int32{
	0,  // 0: InternalApi.RepositoryIntegrator.GetTokenRequest.integration_type:type_name -> InternalApi.RepositoryIntegrator.IntegrationType
	16, // 1: InternalApi.RepositoryIntegrator.GetTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 2: InternalApi.RepositoryIntegrator.CheckTokenResponse.integration_scope:type_name -> InternalApi.RepositoryIntegrator.IntegrationScope
	0,  // 3: InternalApi.RepositoryIntegrator.GetRepositoriesRequest.integration_type:type_name -> InternalApi.RepositoryIntegrator.IntegrationType
	15, // 4: InternalApi.RepositoryIntegrator.GetRepositoriesResponse.repositories:type_name -> InternalApi.RepositoryIntegrator.Repository
	2,  // 5: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.GetToken:input_type -> InternalApi.RepositoryIntegrator.GetTokenRequest
	4,  // 6: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.CheckToken:input_type -> InternalApi.RepositoryIntegrator.CheckTokenRequest
	6,  // 7: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.PreheatFileCache:input_type -> InternalApi.RepositoryIntegrator.PreheatFileCacheRequest
	7,  // 8: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.GetFile:input_type -> InternalApi.RepositoryIntegrator.GetFileRequest
	9,  // 9: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.GithubInstallationInfo:input_type -> InternalApi.RepositoryIntegrator.GithubInstallationInfoRequest
	11, // 10: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.InitGithubInstallation:input_type -> InternalApi.RepositoryIntegrator.InitGithubInstallationRequest
	13, // 11: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.GetRepositories:input_type -> InternalApi.RepositoryIntegrator.GetRepositoriesRequest
	3,  // 12: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.GetToken:output_type -> InternalApi.RepositoryIntegrator.GetTokenResponse
	5,  // 13: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.CheckToken:output_type -> InternalApi.RepositoryIntegrator.CheckTokenResponse
	17, // 14: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.PreheatFileCache:output_type -> google.protobuf.Empty
	8,  // 15: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.GetFile:output_type -> InternalApi.RepositoryIntegrator.GetFileResponse
	10, // 16: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.GithubInstallationInfo:output_type -> InternalApi.RepositoryIntegrator.GithubInstallationInfoResponse
	12, // 17: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.InitGithubInstallation:output_type -> InternalApi.RepositoryIntegrator.InitGithubInstallationResponse
	14, // 18: InternalApi.RepositoryIntegrator.RepositoryIntegratorService.GetRepositories:output_type -> InternalApi.RepositoryIntegrator.GetRepositoriesResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_repository_integrator_proto_init() }
func file_repository_integrator_proto_init() {
	if File_repository_integrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repository_integrator_proto_rawDesc), len(file_repository_integrator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repository_integrator_proto_goTypes,
		DependencyIndexes: file_repository_integrator_proto_depIdxs,
		EnumInfos:         file_repository_integrator_proto_enumTypes,
		MessageInfos:      file_repository_integrator_proto_msgTypes,
	}.Build()
	File_repository_integrator_proto = out.File
	file_repository_integrator_proto_goTypes = nil
	file_repository_integrator_proto_depIdxs = nil
}
