/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the SuperplaneCreateStageBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuperplaneCreateStageBody{}

// SuperplaneCreateStageBody struct for SuperplaneCreateStageBody
type SuperplaneCreateStageBody struct {
	Name *string `json:"name,omitempty"`
	RequesterId *string `json:"requesterId,omitempty"`
	Connections []SuperplaneConnection `json:"connections,omitempty"`
	Conditions []SuperplaneCondition `json:"conditions,omitempty"`
	RunTemplate *SuperplaneRunTemplate `json:"runTemplate,omitempty"`
}

// NewSuperplaneCreateStageBody instantiates a new SuperplaneCreateStageBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuperplaneCreateStageBody() *SuperplaneCreateStageBody {
	this := SuperplaneCreateStageBody{}
	return &this
}

// NewSuperplaneCreateStageBodyWithDefaults instantiates a new SuperplaneCreateStageBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuperplaneCreateStageBodyWithDefaults() *SuperplaneCreateStageBody {
	this := SuperplaneCreateStageBody{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SuperplaneCreateStageBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneCreateStageBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SuperplaneCreateStageBody) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SuperplaneCreateStageBody) SetName(v string) {
	o.Name = &v
}

// GetRequesterId returns the RequesterId field value if set, zero value otherwise.
func (o *SuperplaneCreateStageBody) GetRequesterId() string {
	if o == nil || IsNil(o.RequesterId) {
		var ret string
		return ret
	}
	return *o.RequesterId
}

// GetRequesterIdOk returns a tuple with the RequesterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneCreateStageBody) GetRequesterIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequesterId) {
		return nil, false
	}
	return o.RequesterId, true
}

// HasRequesterId returns a boolean if a field has been set.
func (o *SuperplaneCreateStageBody) HasRequesterId() bool {
	if o != nil && !IsNil(o.RequesterId) {
		return true
	}

	return false
}

// SetRequesterId gets a reference to the given string and assigns it to the RequesterId field.
func (o *SuperplaneCreateStageBody) SetRequesterId(v string) {
	o.RequesterId = &v
}

// GetConnections returns the Connections field value if set, zero value otherwise.
func (o *SuperplaneCreateStageBody) GetConnections() []SuperplaneConnection {
	if o == nil || IsNil(o.Connections) {
		var ret []SuperplaneConnection
		return ret
	}
	return o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneCreateStageBody) GetConnectionsOk() ([]SuperplaneConnection, bool) {
	if o == nil || IsNil(o.Connections) {
		return nil, false
	}
	return o.Connections, true
}

// HasConnections returns a boolean if a field has been set.
func (o *SuperplaneCreateStageBody) HasConnections() bool {
	if o != nil && !IsNil(o.Connections) {
		return true
	}

	return false
}

// SetConnections gets a reference to the given []SuperplaneConnection and assigns it to the Connections field.
func (o *SuperplaneCreateStageBody) SetConnections(v []SuperplaneConnection) {
	o.Connections = v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *SuperplaneCreateStageBody) GetConditions() []SuperplaneCondition {
	if o == nil || IsNil(o.Conditions) {
		var ret []SuperplaneCondition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneCreateStageBody) GetConditionsOk() ([]SuperplaneCondition, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *SuperplaneCreateStageBody) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []SuperplaneCondition and assigns it to the Conditions field.
func (o *SuperplaneCreateStageBody) SetConditions(v []SuperplaneCondition) {
	o.Conditions = v
}

// GetRunTemplate returns the RunTemplate field value if set, zero value otherwise.
func (o *SuperplaneCreateStageBody) GetRunTemplate() SuperplaneRunTemplate {
	if o == nil || IsNil(o.RunTemplate) {
		var ret SuperplaneRunTemplate
		return ret
	}
	return *o.RunTemplate
}

// GetRunTemplateOk returns a tuple with the RunTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneCreateStageBody) GetRunTemplateOk() (*SuperplaneRunTemplate, bool) {
	if o == nil || IsNil(o.RunTemplate) {
		return nil, false
	}
	return o.RunTemplate, true
}

// HasRunTemplate returns a boolean if a field has been set.
func (o *SuperplaneCreateStageBody) HasRunTemplate() bool {
	if o != nil && !IsNil(o.RunTemplate) {
		return true
	}

	return false
}

// SetRunTemplate gets a reference to the given SuperplaneRunTemplate and assigns it to the RunTemplate field.
func (o *SuperplaneCreateStageBody) SetRunTemplate(v SuperplaneRunTemplate) {
	o.RunTemplate = &v
}

func (o SuperplaneCreateStageBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuperplaneCreateStageBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RequesterId) {
		toSerialize["requesterId"] = o.RequesterId
	}
	if !IsNil(o.Connections) {
		toSerialize["connections"] = o.Connections
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.RunTemplate) {
		toSerialize["runTemplate"] = o.RunTemplate
	}
	return toSerialize, nil
}

type NullableSuperplaneCreateStageBody struct {
	value *SuperplaneCreateStageBody
	isSet bool
}

func (v NullableSuperplaneCreateStageBody) Get() *SuperplaneCreateStageBody {
	return v.value
}

func (v *NullableSuperplaneCreateStageBody) Set(val *SuperplaneCreateStageBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSuperplaneCreateStageBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSuperplaneCreateStageBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuperplaneCreateStageBody(val *SuperplaneCreateStageBody) *NullableSuperplaneCreateStageBody {
	return &NullableSuperplaneCreateStageBody{value: val, isSet: true}
}

func (v NullableSuperplaneCreateStageBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuperplaneCreateStageBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


