/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the SuperplaneStageSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuperplaneStageSpec{}

// SuperplaneStageSpec struct for SuperplaneStageSpec
type SuperplaneStageSpec struct {
	Connections []SuperplaneConnection `json:"connections,omitempty"`
	Conditions []SuperplaneCondition `json:"conditions,omitempty"`
	Executor *SuperplaneExecutorSpec `json:"executor,omitempty"`
	Inputs []SuperplaneInputDefinition `json:"inputs,omitempty"`
	InputMappings []SuperplaneInputMapping `json:"inputMappings,omitempty"`
	Outputs []SuperplaneOutputDefinition `json:"outputs,omitempty"`
	Secrets []SuperplaneValueDefinition `json:"secrets,omitempty"`
}

// NewSuperplaneStageSpec instantiates a new SuperplaneStageSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuperplaneStageSpec() *SuperplaneStageSpec {
	this := SuperplaneStageSpec{}
	return &this
}

// NewSuperplaneStageSpecWithDefaults instantiates a new SuperplaneStageSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuperplaneStageSpecWithDefaults() *SuperplaneStageSpec {
	this := SuperplaneStageSpec{}
	return &this
}

// GetConnections returns the Connections field value if set, zero value otherwise.
func (o *SuperplaneStageSpec) GetConnections() []SuperplaneConnection {
	if o == nil || IsNil(o.Connections) {
		var ret []SuperplaneConnection
		return ret
	}
	return o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneStageSpec) GetConnectionsOk() ([]SuperplaneConnection, bool) {
	if o == nil || IsNil(o.Connections) {
		return nil, false
	}
	return o.Connections, true
}

// HasConnections returns a boolean if a field has been set.
func (o *SuperplaneStageSpec) HasConnections() bool {
	if o != nil && !IsNil(o.Connections) {
		return true
	}

	return false
}

// SetConnections gets a reference to the given []SuperplaneConnection and assigns it to the Connections field.
func (o *SuperplaneStageSpec) SetConnections(v []SuperplaneConnection) {
	o.Connections = v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *SuperplaneStageSpec) GetConditions() []SuperplaneCondition {
	if o == nil || IsNil(o.Conditions) {
		var ret []SuperplaneCondition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneStageSpec) GetConditionsOk() ([]SuperplaneCondition, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *SuperplaneStageSpec) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []SuperplaneCondition and assigns it to the Conditions field.
func (o *SuperplaneStageSpec) SetConditions(v []SuperplaneCondition) {
	o.Conditions = v
}

// GetExecutor returns the Executor field value if set, zero value otherwise.
func (o *SuperplaneStageSpec) GetExecutor() SuperplaneExecutorSpec {
	if o == nil || IsNil(o.Executor) {
		var ret SuperplaneExecutorSpec
		return ret
	}
	return *o.Executor
}

// GetExecutorOk returns a tuple with the Executor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneStageSpec) GetExecutorOk() (*SuperplaneExecutorSpec, bool) {
	if o == nil || IsNil(o.Executor) {
		return nil, false
	}
	return o.Executor, true
}

// HasExecutor returns a boolean if a field has been set.
func (o *SuperplaneStageSpec) HasExecutor() bool {
	if o != nil && !IsNil(o.Executor) {
		return true
	}

	return false
}

// SetExecutor gets a reference to the given SuperplaneExecutorSpec and assigns it to the Executor field.
func (o *SuperplaneStageSpec) SetExecutor(v SuperplaneExecutorSpec) {
	o.Executor = &v
}

// GetInputs returns the Inputs field value if set, zero value otherwise.
func (o *SuperplaneStageSpec) GetInputs() []SuperplaneInputDefinition {
	if o == nil || IsNil(o.Inputs) {
		var ret []SuperplaneInputDefinition
		return ret
	}
	return o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneStageSpec) GetInputsOk() ([]SuperplaneInputDefinition, bool) {
	if o == nil || IsNil(o.Inputs) {
		return nil, false
	}
	return o.Inputs, true
}

// HasInputs returns a boolean if a field has been set.
func (o *SuperplaneStageSpec) HasInputs() bool {
	if o != nil && !IsNil(o.Inputs) {
		return true
	}

	return false
}

// SetInputs gets a reference to the given []SuperplaneInputDefinition and assigns it to the Inputs field.
func (o *SuperplaneStageSpec) SetInputs(v []SuperplaneInputDefinition) {
	o.Inputs = v
}

// GetInputMappings returns the InputMappings field value if set, zero value otherwise.
func (o *SuperplaneStageSpec) GetInputMappings() []SuperplaneInputMapping {
	if o == nil || IsNil(o.InputMappings) {
		var ret []SuperplaneInputMapping
		return ret
	}
	return o.InputMappings
}

// GetInputMappingsOk returns a tuple with the InputMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneStageSpec) GetInputMappingsOk() ([]SuperplaneInputMapping, bool) {
	if o == nil || IsNil(o.InputMappings) {
		return nil, false
	}
	return o.InputMappings, true
}

// HasInputMappings returns a boolean if a field has been set.
func (o *SuperplaneStageSpec) HasInputMappings() bool {
	if o != nil && !IsNil(o.InputMappings) {
		return true
	}

	return false
}

// SetInputMappings gets a reference to the given []SuperplaneInputMapping and assigns it to the InputMappings field.
func (o *SuperplaneStageSpec) SetInputMappings(v []SuperplaneInputMapping) {
	o.InputMappings = v
}

// GetOutputs returns the Outputs field value if set, zero value otherwise.
func (o *SuperplaneStageSpec) GetOutputs() []SuperplaneOutputDefinition {
	if o == nil || IsNil(o.Outputs) {
		var ret []SuperplaneOutputDefinition
		return ret
	}
	return o.Outputs
}

// GetOutputsOk returns a tuple with the Outputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneStageSpec) GetOutputsOk() ([]SuperplaneOutputDefinition, bool) {
	if o == nil || IsNil(o.Outputs) {
		return nil, false
	}
	return o.Outputs, true
}

// HasOutputs returns a boolean if a field has been set.
func (o *SuperplaneStageSpec) HasOutputs() bool {
	if o != nil && !IsNil(o.Outputs) {
		return true
	}

	return false
}

// SetOutputs gets a reference to the given []SuperplaneOutputDefinition and assigns it to the Outputs field.
func (o *SuperplaneStageSpec) SetOutputs(v []SuperplaneOutputDefinition) {
	o.Outputs = v
}

// GetSecrets returns the Secrets field value if set, zero value otherwise.
func (o *SuperplaneStageSpec) GetSecrets() []SuperplaneValueDefinition {
	if o == nil || IsNil(o.Secrets) {
		var ret []SuperplaneValueDefinition
		return ret
	}
	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneStageSpec) GetSecretsOk() ([]SuperplaneValueDefinition, bool) {
	if o == nil || IsNil(o.Secrets) {
		return nil, false
	}
	return o.Secrets, true
}

// HasSecrets returns a boolean if a field has been set.
func (o *SuperplaneStageSpec) HasSecrets() bool {
	if o != nil && !IsNil(o.Secrets) {
		return true
	}

	return false
}

// SetSecrets gets a reference to the given []SuperplaneValueDefinition and assigns it to the Secrets field.
func (o *SuperplaneStageSpec) SetSecrets(v []SuperplaneValueDefinition) {
	o.Secrets = v
}

func (o SuperplaneStageSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuperplaneStageSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Connections) {
		toSerialize["connections"] = o.Connections
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.Executor) {
		toSerialize["executor"] = o.Executor
	}
	if !IsNil(o.Inputs) {
		toSerialize["inputs"] = o.Inputs
	}
	if !IsNil(o.InputMappings) {
		toSerialize["inputMappings"] = o.InputMappings
	}
	if !IsNil(o.Outputs) {
		toSerialize["outputs"] = o.Outputs
	}
	if !IsNil(o.Secrets) {
		toSerialize["secrets"] = o.Secrets
	}
	return toSerialize, nil
}

type NullableSuperplaneStageSpec struct {
	value *SuperplaneStageSpec
	isSet bool
}

func (v NullableSuperplaneStageSpec) Get() *SuperplaneStageSpec {
	return v.value
}

func (v *NullableSuperplaneStageSpec) Set(val *SuperplaneStageSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableSuperplaneStageSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableSuperplaneStageSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuperplaneStageSpec(val *SuperplaneStageSpec) *NullableSuperplaneStageSpec {
	return &NullableSuperplaneStageSpec{value: val, isSet: true}
}

func (v NullableSuperplaneStageSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuperplaneStageSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


