/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the SecretLocal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretLocal{}

// SecretLocal Local secrets are stored and managed by SuperPlane itself.
type SecretLocal struct {
	Data *map[string]string `json:"data,omitempty"`
}

// NewSecretLocal instantiates a new SecretLocal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretLocal() *SecretLocal {
	this := SecretLocal{}
	return &this
}

// NewSecretLocalWithDefaults instantiates a new SecretLocal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretLocalWithDefaults() *SecretLocal {
	this := SecretLocal{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SecretLocal) GetData() map[string]string {
	if o == nil || IsNil(o.Data) {
		var ret map[string]string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretLocal) GetDataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SecretLocal) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]string and assigns it to the Data field.
func (o *SecretLocal) SetData(v map[string]string) {
	o.Data = &v
}

func (o SecretLocal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretLocal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableSecretLocal struct {
	value *SecretLocal
	isSet bool
}

func (v NullableSecretLocal) Get() *SecretLocal {
	return v.value
}

func (v *NullableSecretLocal) Set(val *SecretLocal) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretLocal) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretLocal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretLocal(val *SecretLocal) *NullableSecretLocal {
	return &NullableSecretLocal{value: val, isSet: true}
}

func (v NullableSecretLocal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretLocal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


