/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the SuperplaneListSecretsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuperplaneListSecretsResponse{}

// SuperplaneListSecretsResponse struct for SuperplaneListSecretsResponse
type SuperplaneListSecretsResponse struct {
	Secrets []SuperplaneSecret `json:"secrets,omitempty"`
}

// NewSuperplaneListSecretsResponse instantiates a new SuperplaneListSecretsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuperplaneListSecretsResponse() *SuperplaneListSecretsResponse {
	this := SuperplaneListSecretsResponse{}
	return &this
}

// NewSuperplaneListSecretsResponseWithDefaults instantiates a new SuperplaneListSecretsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuperplaneListSecretsResponseWithDefaults() *SuperplaneListSecretsResponse {
	this := SuperplaneListSecretsResponse{}
	return &this
}

// GetSecrets returns the Secrets field value if set, zero value otherwise.
func (o *SuperplaneListSecretsResponse) GetSecrets() []SuperplaneSecret {
	if o == nil || IsNil(o.Secrets) {
		var ret []SuperplaneSecret
		return ret
	}
	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneListSecretsResponse) GetSecretsOk() ([]SuperplaneSecret, bool) {
	if o == nil || IsNil(o.Secrets) {
		return nil, false
	}
	return o.Secrets, true
}

// HasSecrets returns a boolean if a field has been set.
func (o *SuperplaneListSecretsResponse) HasSecrets() bool {
	if o != nil && !IsNil(o.Secrets) {
		return true
	}

	return false
}

// SetSecrets gets a reference to the given []SuperplaneSecret and assigns it to the Secrets field.
func (o *SuperplaneListSecretsResponse) SetSecrets(v []SuperplaneSecret) {
	o.Secrets = v
}

func (o SuperplaneListSecretsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuperplaneListSecretsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Secrets) {
		toSerialize["secrets"] = o.Secrets
	}
	return toSerialize, nil
}

type NullableSuperplaneListSecretsResponse struct {
	value *SuperplaneListSecretsResponse
	isSet bool
}

func (v NullableSuperplaneListSecretsResponse) Get() *SuperplaneListSecretsResponse {
	return v.value
}

func (v *NullableSuperplaneListSecretsResponse) Set(val *SuperplaneListSecretsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSuperplaneListSecretsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSuperplaneListSecretsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuperplaneListSecretsResponse(val *SuperplaneListSecretsResponse) *NullableSuperplaneListSecretsResponse {
	return &NullableSuperplaneListSecretsResponse{value: val, isSet: true}
}

func (v NullableSuperplaneListSecretsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuperplaneListSecretsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


