/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
	"time"
)

// checks if the SuperplaneEventSourceMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuperplaneEventSourceMetadata{}

// SuperplaneEventSourceMetadata struct for SuperplaneEventSourceMetadata
type SuperplaneEventSourceMetadata struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	CanvasId *string `json:"canvasId,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
}

// NewSuperplaneEventSourceMetadata instantiates a new SuperplaneEventSourceMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuperplaneEventSourceMetadata() *SuperplaneEventSourceMetadata {
	this := SuperplaneEventSourceMetadata{}
	return &this
}

// NewSuperplaneEventSourceMetadataWithDefaults instantiates a new SuperplaneEventSourceMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuperplaneEventSourceMetadataWithDefaults() *SuperplaneEventSourceMetadata {
	this := SuperplaneEventSourceMetadata{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SuperplaneEventSourceMetadata) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneEventSourceMetadata) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SuperplaneEventSourceMetadata) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SuperplaneEventSourceMetadata) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SuperplaneEventSourceMetadata) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneEventSourceMetadata) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SuperplaneEventSourceMetadata) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SuperplaneEventSourceMetadata) SetName(v string) {
	o.Name = &v
}

// GetCanvasId returns the CanvasId field value if set, zero value otherwise.
func (o *SuperplaneEventSourceMetadata) GetCanvasId() string {
	if o == nil || IsNil(o.CanvasId) {
		var ret string
		return ret
	}
	return *o.CanvasId
}

// GetCanvasIdOk returns a tuple with the CanvasId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneEventSourceMetadata) GetCanvasIdOk() (*string, bool) {
	if o == nil || IsNil(o.CanvasId) {
		return nil, false
	}
	return o.CanvasId, true
}

// HasCanvasId returns a boolean if a field has been set.
func (o *SuperplaneEventSourceMetadata) HasCanvasId() bool {
	if o != nil && !IsNil(o.CanvasId) {
		return true
	}

	return false
}

// SetCanvasId gets a reference to the given string and assigns it to the CanvasId field.
func (o *SuperplaneEventSourceMetadata) SetCanvasId(v string) {
	o.CanvasId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SuperplaneEventSourceMetadata) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneEventSourceMetadata) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SuperplaneEventSourceMetadata) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *SuperplaneEventSourceMetadata) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o SuperplaneEventSourceMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuperplaneEventSourceMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CanvasId) {
		toSerialize["canvasId"] = o.CanvasId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableSuperplaneEventSourceMetadata struct {
	value *SuperplaneEventSourceMetadata
	isSet bool
}

func (v NullableSuperplaneEventSourceMetadata) Get() *SuperplaneEventSourceMetadata {
	return v.value
}

func (v *NullableSuperplaneEventSourceMetadata) Set(val *SuperplaneEventSourceMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableSuperplaneEventSourceMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableSuperplaneEventSourceMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuperplaneEventSourceMetadata(val *SuperplaneEventSourceMetadata) *NullableSuperplaneEventSourceMetadata {
	return &NullableSuperplaneEventSourceMetadata{value: val, isSet: true}
}

func (v NullableSuperplaneEventSourceMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuperplaneEventSourceMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


