/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the AuthorizationListOrganizationGroupsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizationListOrganizationGroupsResponse{}

// AuthorizationListOrganizationGroupsResponse struct for AuthorizationListOrganizationGroupsResponse
type AuthorizationListOrganizationGroupsResponse struct {
	Groups []string `json:"groups,omitempty"`
}

// NewAuthorizationListOrganizationGroupsResponse instantiates a new AuthorizationListOrganizationGroupsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizationListOrganizationGroupsResponse() *AuthorizationListOrganizationGroupsResponse {
	this := AuthorizationListOrganizationGroupsResponse{}
	return &this
}

// NewAuthorizationListOrganizationGroupsResponseWithDefaults instantiates a new AuthorizationListOrganizationGroupsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizationListOrganizationGroupsResponseWithDefaults() *AuthorizationListOrganizationGroupsResponse {
	this := AuthorizationListOrganizationGroupsResponse{}
	return &this
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *AuthorizationListOrganizationGroupsResponse) GetGroups() []string {
	if o == nil || IsNil(o.Groups) {
		var ret []string
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationListOrganizationGroupsResponse) GetGroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *AuthorizationListOrganizationGroupsResponse) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []string and assigns it to the Groups field.
func (o *AuthorizationListOrganizationGroupsResponse) SetGroups(v []string) {
	o.Groups = v
}

func (o AuthorizationListOrganizationGroupsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizationListOrganizationGroupsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	return toSerialize, nil
}

type NullableAuthorizationListOrganizationGroupsResponse struct {
	value *AuthorizationListOrganizationGroupsResponse
	isSet bool
}

func (v NullableAuthorizationListOrganizationGroupsResponse) Get() *AuthorizationListOrganizationGroupsResponse {
	return v.value
}

func (v *NullableAuthorizationListOrganizationGroupsResponse) Set(val *AuthorizationListOrganizationGroupsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizationListOrganizationGroupsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizationListOrganizationGroupsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizationListOrganizationGroupsResponse(val *AuthorizationListOrganizationGroupsResponse) *NullableAuthorizationListOrganizationGroupsResponse {
	return &NullableAuthorizationListOrganizationGroupsResponse{value: val, isSet: true}
}

func (v NullableAuthorizationListOrganizationGroupsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizationListOrganizationGroupsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


