/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the SuperplaneUpdateStageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuperplaneUpdateStageResponse{}

// SuperplaneUpdateStageResponse struct for SuperplaneUpdateStageResponse
type SuperplaneUpdateStageResponse struct {
	Stage *SuperplaneStage `json:"stage,omitempty"`
}

// NewSuperplaneUpdateStageResponse instantiates a new SuperplaneUpdateStageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuperplaneUpdateStageResponse() *SuperplaneUpdateStageResponse {
	this := SuperplaneUpdateStageResponse{}
	return &this
}

// NewSuperplaneUpdateStageResponseWithDefaults instantiates a new SuperplaneUpdateStageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuperplaneUpdateStageResponseWithDefaults() *SuperplaneUpdateStageResponse {
	this := SuperplaneUpdateStageResponse{}
	return &this
}

// GetStage returns the Stage field value if set, zero value otherwise.
func (o *SuperplaneUpdateStageResponse) GetStage() SuperplaneStage {
	if o == nil || IsNil(o.Stage) {
		var ret SuperplaneStage
		return ret
	}
	return *o.Stage
}

// GetStageOk returns a tuple with the Stage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneUpdateStageResponse) GetStageOk() (*SuperplaneStage, bool) {
	if o == nil || IsNil(o.Stage) {
		return nil, false
	}
	return o.Stage, true
}

// HasStage returns a boolean if a field has been set.
func (o *SuperplaneUpdateStageResponse) HasStage() bool {
	if o != nil && !IsNil(o.Stage) {
		return true
	}

	return false
}

// SetStage gets a reference to the given SuperplaneStage and assigns it to the Stage field.
func (o *SuperplaneUpdateStageResponse) SetStage(v SuperplaneStage) {
	o.Stage = &v
}

func (o SuperplaneUpdateStageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuperplaneUpdateStageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Stage) {
		toSerialize["stage"] = o.Stage
	}
	return toSerialize, nil
}

type NullableSuperplaneUpdateStageResponse struct {
	value *SuperplaneUpdateStageResponse
	isSet bool
}

func (v NullableSuperplaneUpdateStageResponse) Get() *SuperplaneUpdateStageResponse {
	return v.value
}

func (v *NullableSuperplaneUpdateStageResponse) Set(val *SuperplaneUpdateStageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSuperplaneUpdateStageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSuperplaneUpdateStageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuperplaneUpdateStageResponse(val *SuperplaneUpdateStageResponse) *NullableSuperplaneUpdateStageResponse {
	return &NullableSuperplaneUpdateStageResponse{value: val, isSet: true}
}

func (v NullableSuperplaneUpdateStageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuperplaneUpdateStageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


