/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the OrganizationsCreateOrganizationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsCreateOrganizationResponse{}

// OrganizationsCreateOrganizationResponse struct for OrganizationsCreateOrganizationResponse
type OrganizationsCreateOrganizationResponse struct {
	Organization *OrganizationsOrganization `json:"organization,omitempty"`
}

// NewOrganizationsCreateOrganizationResponse instantiates a new OrganizationsCreateOrganizationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsCreateOrganizationResponse() *OrganizationsCreateOrganizationResponse {
	this := OrganizationsCreateOrganizationResponse{}
	return &this
}

// NewOrganizationsCreateOrganizationResponseWithDefaults instantiates a new OrganizationsCreateOrganizationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsCreateOrganizationResponseWithDefaults() *OrganizationsCreateOrganizationResponse {
	this := OrganizationsCreateOrganizationResponse{}
	return &this
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *OrganizationsCreateOrganizationResponse) GetOrganization() OrganizationsOrganization {
	if o == nil || IsNil(o.Organization) {
		var ret OrganizationsOrganization
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsCreateOrganizationResponse) GetOrganizationOk() (*OrganizationsOrganization, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *OrganizationsCreateOrganizationResponse) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given OrganizationsOrganization and assigns it to the Organization field.
func (o *OrganizationsCreateOrganizationResponse) SetOrganization(v OrganizationsOrganization) {
	o.Organization = &v
}

func (o OrganizationsCreateOrganizationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsCreateOrganizationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	return toSerialize, nil
}

type NullableOrganizationsCreateOrganizationResponse struct {
	value *OrganizationsCreateOrganizationResponse
	isSet bool
}

func (v NullableOrganizationsCreateOrganizationResponse) Get() *OrganizationsCreateOrganizationResponse {
	return v.value
}

func (v *NullableOrganizationsCreateOrganizationResponse) Set(val *OrganizationsCreateOrganizationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsCreateOrganizationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsCreateOrganizationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsCreateOrganizationResponse(val *OrganizationsCreateOrganizationResponse) *NullableOrganizationsCreateOrganizationResponse {
	return &NullableOrganizationsCreateOrganizationResponse{value: val, isSet: true}
}

func (v NullableOrganizationsCreateOrganizationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsCreateOrganizationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


