/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the InputMappingValueDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputMappingValueDefinition{}

// InputMappingValueDefinition struct for InputMappingValueDefinition
type InputMappingValueDefinition struct {
	Name *string `json:"name,omitempty"`
	ValueFrom *InputMappingValueFrom `json:"valueFrom,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewInputMappingValueDefinition instantiates a new InputMappingValueDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputMappingValueDefinition() *InputMappingValueDefinition {
	this := InputMappingValueDefinition{}
	return &this
}

// NewInputMappingValueDefinitionWithDefaults instantiates a new InputMappingValueDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputMappingValueDefinitionWithDefaults() *InputMappingValueDefinition {
	this := InputMappingValueDefinition{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InputMappingValueDefinition) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputMappingValueDefinition) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InputMappingValueDefinition) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InputMappingValueDefinition) SetName(v string) {
	o.Name = &v
}

// GetValueFrom returns the ValueFrom field value if set, zero value otherwise.
func (o *InputMappingValueDefinition) GetValueFrom() InputMappingValueFrom {
	if o == nil || IsNil(o.ValueFrom) {
		var ret InputMappingValueFrom
		return ret
	}
	return *o.ValueFrom
}

// GetValueFromOk returns a tuple with the ValueFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputMappingValueDefinition) GetValueFromOk() (*InputMappingValueFrom, bool) {
	if o == nil || IsNil(o.ValueFrom) {
		return nil, false
	}
	return o.ValueFrom, true
}

// HasValueFrom returns a boolean if a field has been set.
func (o *InputMappingValueDefinition) HasValueFrom() bool {
	if o != nil && !IsNil(o.ValueFrom) {
		return true
	}

	return false
}

// SetValueFrom gets a reference to the given InputMappingValueFrom and assigns it to the ValueFrom field.
func (o *InputMappingValueDefinition) SetValueFrom(v InputMappingValueFrom) {
	o.ValueFrom = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *InputMappingValueDefinition) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputMappingValueDefinition) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *InputMappingValueDefinition) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *InputMappingValueDefinition) SetValue(v string) {
	o.Value = &v
}

func (o InputMappingValueDefinition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputMappingValueDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ValueFrom) {
		toSerialize["valueFrom"] = o.ValueFrom
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableInputMappingValueDefinition struct {
	value *InputMappingValueDefinition
	isSet bool
}

func (v NullableInputMappingValueDefinition) Get() *InputMappingValueDefinition {
	return v.value
}

func (v *NullableInputMappingValueDefinition) Set(val *InputMappingValueDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableInputMappingValueDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableInputMappingValueDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputMappingValueDefinition(val *InputMappingValueDefinition) *NullableInputMappingValueDefinition {
	return &NullableInputMappingValueDefinition{value: val, isSet: true}
}

func (v NullableInputMappingValueDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputMappingValueDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


