/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the OrganizationsListOrganizationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsListOrganizationsResponse{}

// OrganizationsListOrganizationsResponse struct for OrganizationsListOrganizationsResponse
type OrganizationsListOrganizationsResponse struct {
	Organizations []OrganizationsOrganization `json:"organizations,omitempty"`
}

// NewOrganizationsListOrganizationsResponse instantiates a new OrganizationsListOrganizationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsListOrganizationsResponse() *OrganizationsListOrganizationsResponse {
	this := OrganizationsListOrganizationsResponse{}
	return &this
}

// NewOrganizationsListOrganizationsResponseWithDefaults instantiates a new OrganizationsListOrganizationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsListOrganizationsResponseWithDefaults() *OrganizationsListOrganizationsResponse {
	this := OrganizationsListOrganizationsResponse{}
	return &this
}

// GetOrganizations returns the Organizations field value if set, zero value otherwise.
func (o *OrganizationsListOrganizationsResponse) GetOrganizations() []OrganizationsOrganization {
	if o == nil || IsNil(o.Organizations) {
		var ret []OrganizationsOrganization
		return ret
	}
	return o.Organizations
}

// GetOrganizationsOk returns a tuple with the Organizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsListOrganizationsResponse) GetOrganizationsOk() ([]OrganizationsOrganization, bool) {
	if o == nil || IsNil(o.Organizations) {
		return nil, false
	}
	return o.Organizations, true
}

// HasOrganizations returns a boolean if a field has been set.
func (o *OrganizationsListOrganizationsResponse) HasOrganizations() bool {
	if o != nil && !IsNil(o.Organizations) {
		return true
	}

	return false
}

// SetOrganizations gets a reference to the given []OrganizationsOrganization and assigns it to the Organizations field.
func (o *OrganizationsListOrganizationsResponse) SetOrganizations(v []OrganizationsOrganization) {
	o.Organizations = v
}

func (o OrganizationsListOrganizationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsListOrganizationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Organizations) {
		toSerialize["organizations"] = o.Organizations
	}
	return toSerialize, nil
}

type NullableOrganizationsListOrganizationsResponse struct {
	value *OrganizationsListOrganizationsResponse
	isSet bool
}

func (v NullableOrganizationsListOrganizationsResponse) Get() *OrganizationsListOrganizationsResponse {
	return v.value
}

func (v *NullableOrganizationsListOrganizationsResponse) Set(val *OrganizationsListOrganizationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsListOrganizationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsListOrganizationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsListOrganizationsResponse(val *OrganizationsListOrganizationsResponse) *NullableOrganizationsListOrganizationsResponse {
	return &NullableOrganizationsListOrganizationsResponse{value: val, isSet: true}
}

func (v NullableOrganizationsListOrganizationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsListOrganizationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


