/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the SuperplaneUpdateSecretResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuperplaneUpdateSecretResponse{}

// SuperplaneUpdateSecretResponse struct for SuperplaneUpdateSecretResponse
type SuperplaneUpdateSecretResponse struct {
	Secret *SuperplaneSecret `json:"secret,omitempty"`
}

// NewSuperplaneUpdateSecretResponse instantiates a new SuperplaneUpdateSecretResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuperplaneUpdateSecretResponse() *SuperplaneUpdateSecretResponse {
	this := SuperplaneUpdateSecretResponse{}
	return &this
}

// NewSuperplaneUpdateSecretResponseWithDefaults instantiates a new SuperplaneUpdateSecretResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuperplaneUpdateSecretResponseWithDefaults() *SuperplaneUpdateSecretResponse {
	this := SuperplaneUpdateSecretResponse{}
	return &this
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *SuperplaneUpdateSecretResponse) GetSecret() SuperplaneSecret {
	if o == nil || IsNil(o.Secret) {
		var ret SuperplaneSecret
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneUpdateSecretResponse) GetSecretOk() (*SuperplaneSecret, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *SuperplaneUpdateSecretResponse) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given SuperplaneSecret and assigns it to the Secret field.
func (o *SuperplaneUpdateSecretResponse) SetSecret(v SuperplaneSecret) {
	o.Secret = &v
}

func (o SuperplaneUpdateSecretResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuperplaneUpdateSecretResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	return toSerialize, nil
}

type NullableSuperplaneUpdateSecretResponse struct {
	value *SuperplaneUpdateSecretResponse
	isSet bool
}

func (v NullableSuperplaneUpdateSecretResponse) Get() *SuperplaneUpdateSecretResponse {
	return v.value
}

func (v *NullableSuperplaneUpdateSecretResponse) Set(val *SuperplaneUpdateSecretResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSuperplaneUpdateSecretResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSuperplaneUpdateSecretResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuperplaneUpdateSecretResponse(val *SuperplaneUpdateSecretResponse) *NullableSuperplaneUpdateSecretResponse {
	return &NullableSuperplaneUpdateSecretResponse{value: val, isSet: true}
}

func (v NullableSuperplaneUpdateSecretResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuperplaneUpdateSecretResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


