/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the SuperplaneCreateCanvasRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuperplaneCreateCanvasRequest{}

// SuperplaneCreateCanvasRequest struct for SuperplaneCreateCanvasRequest
type SuperplaneCreateCanvasRequest struct {
	Canvas *SuperplaneCanvas `json:"canvas,omitempty"`
	RequesterId *string `json:"requesterId,omitempty"`
}

// NewSuperplaneCreateCanvasRequest instantiates a new SuperplaneCreateCanvasRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuperplaneCreateCanvasRequest() *SuperplaneCreateCanvasRequest {
	this := SuperplaneCreateCanvasRequest{}
	return &this
}

// NewSuperplaneCreateCanvasRequestWithDefaults instantiates a new SuperplaneCreateCanvasRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuperplaneCreateCanvasRequestWithDefaults() *SuperplaneCreateCanvasRequest {
	this := SuperplaneCreateCanvasRequest{}
	return &this
}

// GetCanvas returns the Canvas field value if set, zero value otherwise.
func (o *SuperplaneCreateCanvasRequest) GetCanvas() SuperplaneCanvas {
	if o == nil || IsNil(o.Canvas) {
		var ret SuperplaneCanvas
		return ret
	}
	return *o.Canvas
}

// GetCanvasOk returns a tuple with the Canvas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneCreateCanvasRequest) GetCanvasOk() (*SuperplaneCanvas, bool) {
	if o == nil || IsNil(o.Canvas) {
		return nil, false
	}
	return o.Canvas, true
}

// HasCanvas returns a boolean if a field has been set.
func (o *SuperplaneCreateCanvasRequest) HasCanvas() bool {
	if o != nil && !IsNil(o.Canvas) {
		return true
	}

	return false
}

// SetCanvas gets a reference to the given SuperplaneCanvas and assigns it to the Canvas field.
func (o *SuperplaneCreateCanvasRequest) SetCanvas(v SuperplaneCanvas) {
	o.Canvas = &v
}

// GetRequesterId returns the RequesterId field value if set, zero value otherwise.
func (o *SuperplaneCreateCanvasRequest) GetRequesterId() string {
	if o == nil || IsNil(o.RequesterId) {
		var ret string
		return ret
	}
	return *o.RequesterId
}

// GetRequesterIdOk returns a tuple with the RequesterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneCreateCanvasRequest) GetRequesterIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequesterId) {
		return nil, false
	}
	return o.RequesterId, true
}

// HasRequesterId returns a boolean if a field has been set.
func (o *SuperplaneCreateCanvasRequest) HasRequesterId() bool {
	if o != nil && !IsNil(o.RequesterId) {
		return true
	}

	return false
}

// SetRequesterId gets a reference to the given string and assigns it to the RequesterId field.
func (o *SuperplaneCreateCanvasRequest) SetRequesterId(v string) {
	o.RequesterId = &v
}

func (o SuperplaneCreateCanvasRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuperplaneCreateCanvasRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Canvas) {
		toSerialize["canvas"] = o.Canvas
	}
	if !IsNil(o.RequesterId) {
		toSerialize["requesterId"] = o.RequesterId
	}
	return toSerialize, nil
}

type NullableSuperplaneCreateCanvasRequest struct {
	value *SuperplaneCreateCanvasRequest
	isSet bool
}

func (v NullableSuperplaneCreateCanvasRequest) Get() *SuperplaneCreateCanvasRequest {
	return v.value
}

func (v *NullableSuperplaneCreateCanvasRequest) Set(val *SuperplaneCreateCanvasRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSuperplaneCreateCanvasRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSuperplaneCreateCanvasRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuperplaneCreateCanvasRequest(val *SuperplaneCreateCanvasRequest) *NullableSuperplaneCreateCanvasRequest {
	return &NullableSuperplaneCreateCanvasRequest{value: val, isSet: true}
}

func (v NullableSuperplaneCreateCanvasRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuperplaneCreateCanvasRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


