/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the AuthorizationListUserPermissionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizationListUserPermissionsResponse{}

// AuthorizationListUserPermissionsResponse struct for AuthorizationListUserPermissionsResponse
type AuthorizationListUserPermissionsResponse struct {
	UserId *string `json:"userId,omitempty"`
	DomainType *AuthorizationDomainType `json:"domainType,omitempty"`
	DomainId *string `json:"domainId,omitempty"`
	Permissions []AuthorizationPermission `json:"permissions,omitempty"`
}

// NewAuthorizationListUserPermissionsResponse instantiates a new AuthorizationListUserPermissionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizationListUserPermissionsResponse() *AuthorizationListUserPermissionsResponse {
	this := AuthorizationListUserPermissionsResponse{}
	var domainType AuthorizationDomainType = AUTHORIZATIONDOMAINTYPE_DOMAIN_TYPE_UNSPECIFIED
	this.DomainType = &domainType
	return &this
}

// NewAuthorizationListUserPermissionsResponseWithDefaults instantiates a new AuthorizationListUserPermissionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizationListUserPermissionsResponseWithDefaults() *AuthorizationListUserPermissionsResponse {
	this := AuthorizationListUserPermissionsResponse{}
	var domainType AuthorizationDomainType = AUTHORIZATIONDOMAINTYPE_DOMAIN_TYPE_UNSPECIFIED
	this.DomainType = &domainType
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *AuthorizationListUserPermissionsResponse) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationListUserPermissionsResponse) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *AuthorizationListUserPermissionsResponse) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *AuthorizationListUserPermissionsResponse) SetUserId(v string) {
	o.UserId = &v
}

// GetDomainType returns the DomainType field value if set, zero value otherwise.
func (o *AuthorizationListUserPermissionsResponse) GetDomainType() AuthorizationDomainType {
	if o == nil || IsNil(o.DomainType) {
		var ret AuthorizationDomainType
		return ret
	}
	return *o.DomainType
}

// GetDomainTypeOk returns a tuple with the DomainType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationListUserPermissionsResponse) GetDomainTypeOk() (*AuthorizationDomainType, bool) {
	if o == nil || IsNil(o.DomainType) {
		return nil, false
	}
	return o.DomainType, true
}

// HasDomainType returns a boolean if a field has been set.
func (o *AuthorizationListUserPermissionsResponse) HasDomainType() bool {
	if o != nil && !IsNil(o.DomainType) {
		return true
	}

	return false
}

// SetDomainType gets a reference to the given AuthorizationDomainType and assigns it to the DomainType field.
func (o *AuthorizationListUserPermissionsResponse) SetDomainType(v AuthorizationDomainType) {
	o.DomainType = &v
}

// GetDomainId returns the DomainId field value if set, zero value otherwise.
func (o *AuthorizationListUserPermissionsResponse) GetDomainId() string {
	if o == nil || IsNil(o.DomainId) {
		var ret string
		return ret
	}
	return *o.DomainId
}

// GetDomainIdOk returns a tuple with the DomainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationListUserPermissionsResponse) GetDomainIdOk() (*string, bool) {
	if o == nil || IsNil(o.DomainId) {
		return nil, false
	}
	return o.DomainId, true
}

// HasDomainId returns a boolean if a field has been set.
func (o *AuthorizationListUserPermissionsResponse) HasDomainId() bool {
	if o != nil && !IsNil(o.DomainId) {
		return true
	}

	return false
}

// SetDomainId gets a reference to the given string and assigns it to the DomainId field.
func (o *AuthorizationListUserPermissionsResponse) SetDomainId(v string) {
	o.DomainId = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *AuthorizationListUserPermissionsResponse) GetPermissions() []AuthorizationPermission {
	if o == nil || IsNil(o.Permissions) {
		var ret []AuthorizationPermission
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationListUserPermissionsResponse) GetPermissionsOk() ([]AuthorizationPermission, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *AuthorizationListUserPermissionsResponse) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []AuthorizationPermission and assigns it to the Permissions field.
func (o *AuthorizationListUserPermissionsResponse) SetPermissions(v []AuthorizationPermission) {
	o.Permissions = v
}

func (o AuthorizationListUserPermissionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizationListUserPermissionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.DomainType) {
		toSerialize["domainType"] = o.DomainType
	}
	if !IsNil(o.DomainId) {
		toSerialize["domainId"] = o.DomainId
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return toSerialize, nil
}

type NullableAuthorizationListUserPermissionsResponse struct {
	value *AuthorizationListUserPermissionsResponse
	isSet bool
}

func (v NullableAuthorizationListUserPermissionsResponse) Get() *AuthorizationListUserPermissionsResponse {
	return v.value
}

func (v *NullableAuthorizationListUserPermissionsResponse) Set(val *AuthorizationListUserPermissionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizationListUserPermissionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizationListUserPermissionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizationListUserPermissionsResponse(val *AuthorizationListUserPermissionsResponse) *NullableAuthorizationListUserPermissionsResponse {
	return &NullableAuthorizationListUserPermissionsResponse{value: val, isSet: true}
}

func (v NullableAuthorizationListUserPermissionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizationListUserPermissionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


