/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the AuthorizationDescribeRoleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizationDescribeRoleResponse{}

// AuthorizationDescribeRoleResponse struct for AuthorizationDescribeRoleResponse
type AuthorizationDescribeRoleResponse struct {
	Role *AuthorizationRole `json:"role,omitempty"`
}

// NewAuthorizationDescribeRoleResponse instantiates a new AuthorizationDescribeRoleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizationDescribeRoleResponse() *AuthorizationDescribeRoleResponse {
	this := AuthorizationDescribeRoleResponse{}
	return &this
}

// NewAuthorizationDescribeRoleResponseWithDefaults instantiates a new AuthorizationDescribeRoleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizationDescribeRoleResponseWithDefaults() *AuthorizationDescribeRoleResponse {
	this := AuthorizationDescribeRoleResponse{}
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *AuthorizationDescribeRoleResponse) GetRole() AuthorizationRole {
	if o == nil || IsNil(o.Role) {
		var ret AuthorizationRole
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationDescribeRoleResponse) GetRoleOk() (*AuthorizationRole, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *AuthorizationDescribeRoleResponse) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given AuthorizationRole and assigns it to the Role field.
func (o *AuthorizationDescribeRoleResponse) SetRole(v AuthorizationRole) {
	o.Role = &v
}

func (o AuthorizationDescribeRoleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizationDescribeRoleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

type NullableAuthorizationDescribeRoleResponse struct {
	value *AuthorizationDescribeRoleResponse
	isSet bool
}

func (v NullableAuthorizationDescribeRoleResponse) Get() *AuthorizationDescribeRoleResponse {
	return v.value
}

func (v *NullableAuthorizationDescribeRoleResponse) Set(val *AuthorizationDescribeRoleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizationDescribeRoleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizationDescribeRoleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizationDescribeRoleResponse(val *AuthorizationDescribeRoleResponse) *NullableAuthorizationDescribeRoleResponse {
	return &NullableAuthorizationDescribeRoleResponse{value: val, isSet: true}
}

func (v NullableAuthorizationDescribeRoleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizationDescribeRoleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


