/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the SuperplaneDescribeStageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuperplaneDescribeStageResponse{}

// SuperplaneDescribeStageResponse struct for SuperplaneDescribeStageResponse
type SuperplaneDescribeStageResponse struct {
	Stage *SuperplaneStage `json:"stage,omitempty"`
}

// NewSuperplaneDescribeStageResponse instantiates a new SuperplaneDescribeStageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuperplaneDescribeStageResponse() *SuperplaneDescribeStageResponse {
	this := SuperplaneDescribeStageResponse{}
	return &this
}

// NewSuperplaneDescribeStageResponseWithDefaults instantiates a new SuperplaneDescribeStageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuperplaneDescribeStageResponseWithDefaults() *SuperplaneDescribeStageResponse {
	this := SuperplaneDescribeStageResponse{}
	return &this
}

// GetStage returns the Stage field value if set, zero value otherwise.
func (o *SuperplaneDescribeStageResponse) GetStage() SuperplaneStage {
	if o == nil || IsNil(o.Stage) {
		var ret SuperplaneStage
		return ret
	}
	return *o.Stage
}

// GetStageOk returns a tuple with the Stage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneDescribeStageResponse) GetStageOk() (*SuperplaneStage, bool) {
	if o == nil || IsNil(o.Stage) {
		return nil, false
	}
	return o.Stage, true
}

// HasStage returns a boolean if a field has been set.
func (o *SuperplaneDescribeStageResponse) HasStage() bool {
	if o != nil && !IsNil(o.Stage) {
		return true
	}

	return false
}

// SetStage gets a reference to the given SuperplaneStage and assigns it to the Stage field.
func (o *SuperplaneDescribeStageResponse) SetStage(v SuperplaneStage) {
	o.Stage = &v
}

func (o SuperplaneDescribeStageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuperplaneDescribeStageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Stage) {
		toSerialize["stage"] = o.Stage
	}
	return toSerialize, nil
}

type NullableSuperplaneDescribeStageResponse struct {
	value *SuperplaneDescribeStageResponse
	isSet bool
}

func (v NullableSuperplaneDescribeStageResponse) Get() *SuperplaneDescribeStageResponse {
	return v.value
}

func (v *NullableSuperplaneDescribeStageResponse) Set(val *SuperplaneDescribeStageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSuperplaneDescribeStageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSuperplaneDescribeStageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuperplaneDescribeStageResponse(val *SuperplaneDescribeStageResponse) *NullableSuperplaneDescribeStageResponse {
	return &NullableSuperplaneDescribeStageResponse{value: val, isSet: true}
}

func (v NullableSuperplaneDescribeStageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuperplaneDescribeStageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


