/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the SuperplaneValueFromSecret type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuperplaneValueFromSecret{}

// SuperplaneValueFromSecret struct for SuperplaneValueFromSecret
type SuperplaneValueFromSecret struct {
	Name *string `json:"name,omitempty"`
	Key *string `json:"key,omitempty"`
}

// NewSuperplaneValueFromSecret instantiates a new SuperplaneValueFromSecret object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuperplaneValueFromSecret() *SuperplaneValueFromSecret {
	this := SuperplaneValueFromSecret{}
	return &this
}

// NewSuperplaneValueFromSecretWithDefaults instantiates a new SuperplaneValueFromSecret object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuperplaneValueFromSecretWithDefaults() *SuperplaneValueFromSecret {
	this := SuperplaneValueFromSecret{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SuperplaneValueFromSecret) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneValueFromSecret) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SuperplaneValueFromSecret) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SuperplaneValueFromSecret) SetName(v string) {
	o.Name = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *SuperplaneValueFromSecret) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneValueFromSecret) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *SuperplaneValueFromSecret) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *SuperplaneValueFromSecret) SetKey(v string) {
	o.Key = &v
}

func (o SuperplaneValueFromSecret) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuperplaneValueFromSecret) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	return toSerialize, nil
}

type NullableSuperplaneValueFromSecret struct {
	value *SuperplaneValueFromSecret
	isSet bool
}

func (v NullableSuperplaneValueFromSecret) Get() *SuperplaneValueFromSecret {
	return v.value
}

func (v *NullableSuperplaneValueFromSecret) Set(val *SuperplaneValueFromSecret) {
	v.value = val
	v.isSet = true
}

func (v NullableSuperplaneValueFromSecret) IsSet() bool {
	return v.isSet
}

func (v *NullableSuperplaneValueFromSecret) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuperplaneValueFromSecret(val *SuperplaneValueFromSecret) *NullableSuperplaneValueFromSecret {
	return &NullableSuperplaneValueFromSecret{value: val, isSet: true}
}

func (v NullableSuperplaneValueFromSecret) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuperplaneValueFromSecret) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


